post http://localhost:3000/register/
Content-Type: application/json

{
  "username": "venky123",
  "name": "venkey",
  "password": "masana",
  "gender": "male",
  "location": "nellore"
}

post http://localhost:3000/login/
Content-Type: application/json

{
  "username": "venky123",
  "password": "masana"
}

put http://localhost:3000/change-password/
Content-Type: application/json

{
  "username": "venky123",
  "oldPassword": "masa",
  "newPassword": "masa"
}
